import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProviderWrapper } from "@/providers/AuthProviderWrapper";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ClientLayoutWrapper from "@/components/ClientLayoutWrapper/ClientLayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learning Mate AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
          <AuthProviderWrapper>
            <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
          </AuthProviderWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
